name: $(Build.SourceBranchName)_$(Build.Reason)_$(majorVersion).$(Build.BuildId)$(Rev:.r)
variables:
  buildConfiguration: Release
  majorVersion: 0.0.0

# Enable PR validation on branches master and dev
pr:
  branches:
    include:
      - master
      - dev

# Enable CI on branches master and dev
# Batch builds
trigger:
  batch: true
  branches:
    include:
      - dev
      - master

continueOnError: false
pool:
  name: 1ES-Hosted-Azfunc
  demands:
    - ImageOverride -equals MMSUbuntu20.04TLS



steps:
  - bash: |
      curl -sSL https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh | bash /dev/stdin -v '6.0.100-rc.2.21505.57' -c 'release' --install-dir /usr/share/dotnet
    displayName: 'Install the .Net version used by the Core Tools for Linux'
  
  - pwsh: |
      .\script\setup-test-pipeline.ps1
    displayName: 'Setup test environment -- Install the Core Tools'

  - task: JavaToolInstaller@0
    displayName: Install Java
    inputs:
      versionSpec: '8'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Bash@3
    displayName: Run Java Function
    inputs:
      targetType: filePath
      filePath: ./script/run_function.sh
