name: $(Build.SourceBranchName)_$(Build.Reason)_$(majorVersion).$(Build.BuildId)$(Rev:.r)
variables:
  buildConfiguration: 'Release'
  majorVersion: 0.0.0

# Enable PR validation on branches master and dev
pr:
  branches:
    include:
    - master
    - dev

# Enable CI on branches master and dev
# Batch builds
trigger:
  batch: true
  branches:
    include:
    - dev
    - master

jobs:

- job: build_and_test
  displayName: 'Build and Test'
  continueOnError: false
  pool:
    vmImage: 'Ubuntu 16.04'
  
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      projects: .

  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: test
      projects: ./test/Microsoft.Azure.WebJobs.Extensions.Kafka.UnitTests

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'

  - task: Bash@3
    displayName: 'Start kafka in single node'
    inputs:
      targetType: filePath
      filePath: './test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests/start-kafka-test-environment.sh'
      workingDirectory: test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests

  - task: DotNetCoreCLI@2
    displayName: 'Run e2e tests'
    inputs:
      command: test
      projects: ./test/Microsoft.Azure.WebJobs.Extensions.Kafka.EndToEndTests

  - script: dotnet pack -o '$(Build.ArtifactStagingDirectory)' --include-symbols src/Microsoft.Azure.WebJobs.Extensions.Kafka/Microsoft.Azure.WebJobs.Extensions.Kafka.csproj
    displayName: 'Pack nuget pacakge'

  - task: EsrpCodeSigning@1
    displayName: 'ESRP CodeSigning: Nupkg'
    condition: and(succeeded(), not(variables['System.PullRequest.PullRequestNumber']))
    inputs:
      ConnectedServiceName: 'b12af24c-362b-4e79-bd63-61977b0007a3'
      FolderPath: '$(Build.ArtifactStagingDirectory)'
      Pattern: '*.nupkg'
      signConfigType: 'inlineSignParams'
      inlineOperation: '[
    {
      "KeyCode": "CP-401405",
      "OperationCode": "NuGetSign",
      "Parameters": {},
      "ToolName": "sign",
      "ToolVersion": "1.0"
    },
    {
      "KeyCode": "CP-401405",
      "OperationCode": "NuGetVerify",
      "Parameters": {},
      "ToolName": "sign",
      "ToolVersion": "1.0"
    }
]'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
