trigger:
  branches:
    include:
      - master
      # release
      - 4.x.x
      - 4.x.x-*

resources:
  repositories:
    - repository: eng
      type: git
      name: engineering
      ref: refs/tags/release

variables:
  - template: ci/variables/cfs.yml@eng

extends:
  template: ci/code-mirror.yml@eng
